spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver #driver class name for postgresql
  jpa:
    hibernate:
      ddl-auto: create-drop #everytime the application starts, it will drop the tables and create them again
#    show-sql: true #show the sql queries in the console
    properties:
      hibernate:
        format_sql: true #format the sql queries in the console
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect #use the postgresql dialect